### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by heavywatal** [lorrainea/CNEFinder#11]
The help message and [wiki/Input-Files](https://github.com/lorrainea/CNEFinder/wiki/Input-Files) state that `cnef` reads GTF/GFF files with `-e`, `-f`, `-g`, and `-j`. But feeding GFF files generates `Error: Reference exon file format is incorrect.`. The files in [Experiments/Files](https://github.com/lorrainea/CNEFinder/tree/master/Experiments/Files) are accepted but they are not GTF/GFF format. What are the exact specifications of the input format?

**Comment by lorrainea** [comment]
Yes the source and feature columns seem to be missing, but please use the format of the files in the experiments/files page. There are instructions on how to produce these files.

**Comment by heavywatal** [comment]
Sorry I could not find instructions to generate valid input files.
https://github.com/lorrainea/CNEFinder/wiki/Input-Files
This tells only how to obtain an R object like `exonsRanges`. Is there any function like `rtracklayer::export.gff3()` to generate custom cnef format?

Anyway the documentations are wrong and GTF/GFF should not be mentioned there.

**Comment by dpolychr** [comment]
Thanks for pointing this out @heavywatal, and also thanks for using CNEFinder! You are right, technically the GTF/GFF format is not used as input however I believe you can extract the corresponding fields from such a file and bring it to the format given in the example / required by CNEFinder for exons. I will update the documentation to make this more clear.

**Comment by margaretwoodhouse** [comment]
Hi, there:

I'm very excited to use CNEfinder, but I keep getting a segmentation fault when I run it on my own files. The error is

query_exons[ num_seqs_f ] = NULL;

My query exon file is formatted as:

chr1 44289	44947	.	0	+
chr1	45666	45803	.	0	+
chr1	45888	46133	.	0	+
chr1	46229	46342	.	0	+
chr1	46451	46633	.	0	+
chr1	47045	47262	.	0	+
chr1	47650	48111	.	0	+

I was able to run the test files successfully, but when I try to run my own exon files on my own masked genomes, I keep getting segmentation errors, even though as far as I can tell, I have formatted my exon files exactly as the test files are formatted. What could be going wrong?  

my command:

cnef  -r rice.fa  -q maize.fa  -e rice_exons  -f maize_exons -y 3 -z 1  -a 189697 -b 1715993 -c 359628 -d 2156208 -t 0.95 -l 150 -o output2

It would help if I knew exactly what the format was that the program was looking for. 

Thanks!

**Comment by lorrainea** [comment]
Hi, could you please send over all the input files you are using to help me identify where the error is coming from.

Thanks

**Comment by margaretwoodhouse** [comment]
[rice-maize-exon-files.tar.gz](https://github.com/lorrainea/CNEFinder/files/4983171/rice-maize-exon-files.tar.gz)
Hi there:

My fasta files are way too big to upload here, but attached are the exon files I used; I have two versions, file_exons and file_exons2, the latter where I made sure the entries were sorted by chromosome the same way the fasta file chromosomes are ordered. Fasta files are formatted >chr1, >chr2, etc, and only include the pseudomolecules with all scaffolds and plastids removed, and these are also not present in the exon files.

**Comment by margaretwoodhouse** [comment]
Here are where I got the files (without the scaffolds/plastids removed):
maize:
ftp://ftp.ensemblgenomes.org/pub/plants/release-37/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.toplevel.fa.gz

rice:
ftp://ftp.ensemblgenomes.org/pub/plants/release-37/fasta/oryza_sativa/dna/Oryza_sativa.IRGSP-1.0.dna.toplevel.fa.gz

**Comment by lorrainea** [comment]
Your exon files were in the right format, there was a small bug which has now been fixed. Please pull the changes and try now. Thanks

**Comment by margaretwoodhouse** [comment]
Yes, the bug is fixed and the program works now on my files. Thanks so much!

**Comment by heavywatal** [comment]
The original problem has not been addressed yet. The options `-e`, `-f`, `-g`, and `-j` do not accept GTF/GFF files. If the implementation is not going to be changed, then at least the documentation should be updated to make it clear.
