### ISSUE TITLE
Trooble with chromosome name pattern

### ISSUE THREAD

**Issue by El-Castor** [lorrainea/CNEFinder#12]
Hi, 

thanks for this useful tools. I testing it with arabidopsis TAIR10 genome and my custome genome but I have an error : 

```bash
Pre-processing data
 Error: Chromosome CHR1	 not found in reference genome!
```

I now that my chromosome pattern name of the necessary input file (exons, gene and fasta files) is not like this "CHRX" , as the arabidopsis genome too. 

You have hard coded the chromosome name ? 

It is possible to custom you code to avoid the switch of my custom genome chromosome name ?if right, in which script can I change it. I think it will be better to keep the chromosome name on a chromSize file for example. This avoid the fact to have the good chromosome name pattern.

Thanks in advance

**Comment by lorrainea** [comment]
Hi, this is a simple fix, you just need to comment out the following lines in cnef.cc and run make again:
829
839
912
920

Note when you write your chromosome name in the terminal, it cannot have empty spaces, to deal with this you will need to escape the spaces in your input the chromosome name with \.

For example "-y name of chromosome" would need to be input as "-y name\ of\ chromosome"

**Comment by El-Castor** [comment]
Hi Lorrainea, 

Sorry to answer so late, but under the current sanitary conditions I could no longer work on this subject.

However, thank you for your response.
I have changed the lines:

```c
chromosome_g1.insert (0, "CHR");
```

by

```c
chromosome_g1.insert (0, "");
```

because if I comment out the lines you suggested to me I can no longer compile the code.

However after this modification I found an error when launching the pipeline:

```bash
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso11_cucumismelo_masked.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//TAIR10_arabido_masked.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso_exons
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//tair10_exons
 Pre-processing data
 Error: Chromosome 1	 not found in reference genome!
```

here you have the command that I use to launch CNEfinder : 
```bash
refGenome="CMiso11_cucumismelo_masked.fa"
queryGenome="TAIR10_arabido_masked.fa"

exonsRef="CMiso_exons"
exonsQuery="tair10_exons"



### OUTPUT ###
outputDir="/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/CNE_analysis/out"
mkdir -p $outputDir

### OPTION ###

similarityThreshold=0.95
CSEsizeOption=70

threadOption=12

### MAIN ###


${softDir}/cnef -r ${ressourcesDir}/$refGenome -q ${ressourcesDir}/$queryGenome -e ${ressourcesDir}/$exonsRef -f ${ressourcesDir}/$exonsQuery -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t $similarityThreshold -l ${CSEsizeOption} -o $outputDir -T $threadOption


```

Below you have an head of the two file CMiso11_cucumismelo_masked.fa and TAIR10_arabido_masked.fa respectively and only related to the chromosome names pattern : 

```bash
>CMiso1.1chr00
>CMiso1.1chr01
>CMiso1.1chr02
>CMiso1.1chr03
>CMiso1.1chr04
>CMiso1.1chr05
>CMiso1.1chr06
>CMiso1.1chr07
>CMiso1.1chr08
>CMiso1.1chr09
```

```bash
>1
>2
>3
>4
>5
>mitochondria
>chloroplast

```
and Now an head of the exons file : 

```bash
CMiso1.1chr00	88924	89786	CMiso1.1chr00g0280571	0	-
CMiso1.1chr00	89887	92091	CMiso1.1chr00g0280571	0	-
CMiso1.1chr00	280551	280643	CMiso1.1chr00g0280921	0	+
CMiso1.1chr00	280724	280813	CMiso1.1chr00g0280921	0	+
CMiso1.1chr00	307393	307739	CMiso1.1chr00g0280981	0	-
CMiso1.1chr00	307793	307814	CMiso1.1chr00g0280981	0	-
CMiso1.1chr00	429671	429770	CMiso1.1chr00g0281021	0	+
CMiso1.1chr00	429837	429962	CMiso1.1chr00g0281021	0	+
CMiso1.1chr00	430358	430542	CMiso1.1chr00g0281021	0	+
CMiso1.1chr00	727520	729088	CMiso1.1chr00g0281221	0	+

```

```bash
Chr1	3631	3913	.	0	+
Chr1	3996	4276	.	0	+
Chr1	4486	4605	.	0	+
Chr1	4706	5095	.	0	+
Chr1	5174	5326	.	0	+
Chr1	5439	5899	.	0	+
Chr1	8571	8737	.	0	-
Chr1	8417	8464	.	0	-
Chr1	8236	8325	.	0	-
Chr1	7942	7987	.	0	-
```


Do you have any suggestion or see what I am doing wrong please ? 

Thanks in advance

**Comment by lorrainea** [comment]
Hi, you are using -y 1 and -z 1 which means you are looking for the chromosomes named "1" within file CMiso11_cucumismelo_masked.fa as well as file TAIR10_arabido_masked.fa. However, it seems that they do not have chromosomes named "1".

Could you please send me file files you are using as input?

**Comment by El-Castor** [comment]
Hi Lorrainea, 

Thanks to respond, finally I was able to launch it with my custom chromosome name. I am very sorry I have do a mistake in the set up of the query and reference genome... Sorry to waste your time with this kind of mistake. 

Unfortunately I Have an error at the end of the pipeline when the script write the output.You can see here my two slurm out and err log file:

slurm.log.err:
```bash
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso11_cucumismelo_masked.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//TAIR10_arabido_masked_chromomsePatternTest2.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso_exons
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//tair10_exons
 Pre-processing data
 Computing CNEs with minimum length 70, maximum length 2000 and similarity threshold 95.00% 
 -Identifying maximal exact matches of minimum length 18
```

slurm.log.out:

```bash
ERROR: unable to open new_ref_/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/CNE_analysis/out.fa file
```

Do you want that I open a new issue ? If not do you have any suggestion ?

Thanks in advance

**Comment by lorrainea** [comment]
Hi

Thank you for noticing this, I have pushed some new changes. Please pull them and make your changes again as you previously did and try to rerun.

Thanks

**Comment by El-Castor** [comment]
Hi Lorrainea, 

Thanks for you update. I have push the new changes and change the ligne that cause issues with my chromosome name pattern. 
Before launch it again (because it take some times to compute in my cluster, more or less 1 day and half) I want to be sure of my launch command for the all argument. Can you check my sbatch below and tell me If I do a mistake please ?

```bash
#!/bin/bash
#
#SBATCH -J CNE_finder # le nom de votre job
#SBATCH -p big # la partition
#SBATCH -n 12 # nombre de processeurs
#SBATCH -N 1 # nombre de noeuds, DO NOT CHANGE THIS SETTING
#SBATCH --mem 40000 # mémoire (en MB)
#SBATCH -o slurm.%N.%j.out # la sortie standard
#SBATCH -e slurm.%N.%j.err # la sortie erreur standard
#SBATCH --mail-type=END # notification par e-mail à la fin en cas de réussite ou erreur
#SBATCH --mail-user=clement.pichot@u-psud.fr # l’adresse e-mail

export PATH="/opt/share/FLOCAD/userspace/cpichot/miniconda3/bin/:$PATH"

source activate CNEfinder

### INPUT ###
softDir="/NetScratch/cpichot/soft/CNEFinder"

ressourcesDir="/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources/"

refGenome="CMiso11_cucumismelo_masked.fa"
queryGenome="TAIR10_arabido_masked_chromomsePatternTest2.fa"

exonsRef="CMiso_exons"
exonsQuery="tair10_exons"



### OUTPUT ###
outputDir="onew_ref_out_chr1_CMisoVsTair"
mkdir -p $outputDir

### OPTION ###

similarityThreshold=0.95
CSEsizeOption=70

threadOption=12

### MAIN ###


${softDir}/cnef -r ${ressourcesDir}/$refGenome -q ${ressourcesDir}/$queryGenome -e ${ressourcesDir}/$exonsRef -f ${ressourcesDir}/$exonsQuery -y CMiso1.1chr01 -z Chr1 -a 0 -b 0 -c 0 -d 0 -t $similarityThreshold -l ${CSEsizeOption} -o $outputDir -T $threadOption

```

thanks

**Comment by lorrainea** [comment]
Hi, please note that the output of CNEFinder is a BED file and not a directory
You have used -o $outputDir in your command which corresponds to the directory 'onew_ref_out_chr1_CMisoVsTair' you have created, but a file name should follow from the -o parameter.

**Comment by El-Castor** [comment]
Hi, 
 Thanks to take time to response. So I have correct my sbatch lik this : 

```bash
### INPUT ###
softDir="/NetScratch/cpichot/soft/CNEFinder"

ressourcesDir="/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources/"

refGenome="CMiso11_cucumismelo_masked.fa"
queryGenome="TAIR10_arabido_masked_chromomsePatternTest2.fa"

exonsRef="CMiso_exons"
exonsQuery="tair10_exons"



### OUTPUT ###
outputDir="/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/CNE_analysis"
mkdir -p $outputDir

outputFileName="new_ref_out_chr1_CMisoVsTair.bed"

### OPTION ###

similarityThreshold=0.95
CSEsizeOption=70

threadOption=12

### MAIN ###


${softDir}/cnef -r ${ressourcesDir}/$refGenome -q ${ressourcesDir}/$queryGenome -e ${ressourcesDir}/$exonsRef -f ${ressourcesDir}/$exonsQuery -y CMiso1.1chr01 -z Chr1 -a 0 -b 0 -c 0 -d 0 -t $similarityThreshold -l ${CSEsizeOption} -o $outputDir/$outputFileName -T $threadOption

```

I have understand right ?

**Comment by lorrainea** [comment]
Hi, yes this is correct

**Comment by El-Castor** [comment]
Thanks a lot for your time. I will launch the analysis and close the post when it's correctly done.

**Comment by lorrainea** [comment]
Great, let me know if you have any further questions.

**Comment by El-Castor** [comment]
Hi Lorrainea, 

Finally I get a bed file a the end of analysis. But It still some tmp folder in my output directory and I have a log error message from slurm. I don't know if it normal or not. 

Here you can find an ls of my output directory : 

 ```bash
total 65984
drwxr-xr-x 1  utilisateurs      440 oct.  23 15:52 .
drwxr-xr-x 1  utilisateurs      552 oct.  23 15:54 ..
drwxr-x--- 1 utilisateurs      644 oct.  22 02:30 9521_tmp
-rw-r--r-- 1  utilisateurs   647608 oct.  22 20:35 new_ref_out_chr1_CMisoVsTair.bed
-rw-r--r-- 1  utilisateurs 30427786 oct.  22 02:28 new_ref_out_chr1_CMisoVsTair.bed_new_query.fa
-rw-r--r-- 1  utilisateurs 35819284 oct.  22 02:28 new_ref_out_chr1_CMisoVsTair.bed_new_ref.fa
-rw-r--r-- 1  utilisateurs   647608 oct.  23 15:48 new_ref_out_chr1_CMisoVsTair_chrTrueName.bed
-rw-r--r-- 1  utilisateurs      876 oct.  22 20:35 slurm.node8.145804.err
-rw-r--r-- 1  utilisateurs        0 oct.  21 17:22 slurm.node8.145804.out
```

And here this the output log file of slurm :

```bash
Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso11_cucumismelo_masked.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//TAIR10_arabido_masked_chromomsePatternTest2.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso_exons
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//tair10_exons
 Pre-processing data
 Computing CNEs with minimum length 70, maximum length 2000 and similarity threshold 95.00% 
 -Identifying maximal exact matches of minimum length 18
 -Merging 15483880 maximal exact matches
 -Extending 732049 merged matches of minimum length 35, with an additional extension threshold of 0.05
 Preparing the output
Elapsed time: 65168.217326 secs.

``` 
Everything is normal for you ?

Instead of these "issues" if I can called it like that I have the bed output file with CNE.

**Comment by lorrainea** [comment]
Hi, this shows that CNEFinder completed successfully as it should. Your output CNEs should be visible in your new_ref_out_chr1_CMisoVsTair.bed file.

**Comment by El-Castor** [comment]
hi, 

Ok great, thanks a lot for your help and your time. I have another question for whole genome CNE searching but it is not related with the initial issues. Do I re-open the corresponding post from the 31 Jully ?

**Comment by lorrainea** [comment]
I already reopened your initial issue. You can just reply to this comment with your new question.

**Comment by El-Castor** [comment]
Sorry, I misunderstood. I would like to start the analysis by directly comparing two whole genomes (this question was already asked on July 31 and a post was opened and then closed because no answer from the author of the question). So I wanted to know if I reopen this post or continue on this one?

In other words, I need to compare the two whole genome and not only on chromosome. Because if not I have relaunch the analysis for each chromosome comparison that is a little bit fastidious. 

Thanks in advance

**Comment by lorrainea** [comment]
Ok I see, please try the following:

You can do this using the following method to allow CNEFinder to work on an entire genome rather than a specific chromosome:
Concatenate all chromosomes into a single Fasta file.
Instead of inputting the chromosome name for parameters x and y, use the id name you have given for the genome files.

**Comment by El-Castor** [comment]
Ok thanks a lot I will try it. 
regards

**Comment by El-Castor** [comment]
Hi lorrainea, 

I have try that you suggest but I get an error after running the command. 

Here you have the sbatch to launch CNEfinder  on whole genome : 

```bash

### INPUT ###
softDir="/NetScratch/cpichot/soft/CNEFinder"

ressourcesDir="/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources/"

refGenome="CMiso11_cucumismelo_masked.fa"
queryGenome="TAIR10_arabido_masked_chromomsePatternTest2.fa"

exonsRef="CMiso_exons"
exonsQuery="tair10_exons"



### OUTPUT ###
outputDir="/NetScratch/cpichot/cisRegElement_prediction/CSEfinder/CNE_analysis"
mkdir -p $outputDir

outputFileName="new_ref_out_wholeGen_CMisoVsTair_sizeMin70.bed"

### OPTION ###

similarityThreshold=0.95
CSEsizeOption=70

threadOption=12

### MAIN ###


${softDir}/cnef -r ${ressourcesDir}/$refGenome -q ${ressourcesDir}/$queryGenome -e ${ressourcesDir}/$exonsRef -f ${ressourcesDir}/$exonsQuery -y $refGenome -z $queryGenome -a 0 -b 0 -c 0 -d 0 -t $similarityThreshold -l ${CSEsizeOption} -o $outputDir/$outputFileName -T $threadOption

```

and here the error message : 

```bash
cat slurm.node8.189298.CNE_finder_wholeGen.err
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso11_cucumismelo_masked.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//TAIR10_arabido_masked_chromomsePatternTest2.fa
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//CMiso_exons
 Reading the file: /NetScratch/cpichot/cisRegElement_prediction/CSEfinder/pre-processing/ressources//tair10_exons
 Pre-processing data
 Error: Chromosome CMISO11_CUCUMISMELO_MASKED.FA	 not found in reference genome!

```

I think I didn't understand  how I can fill in the filename instead of the chromosome name...

Do you have suggestion ?

Thanks in advance

**Comment by lorrainea** [comment]
Hi, so what you have used for the chromosome name is the name of the file. However what you should use for the chromosome name is the fasta ID name (the name you have given to your fasta sequence inside the fa file, which comes after the '>' symbol).

For example, "CMiso11_cucumismelo_masked.fa" is the name of your reference genome, but what ID have you used within this file?

**Comment by El-Castor** [comment]
Hi, 

Ok I understand my errors. I have a question. If I concatenate all chromosomes, how I can get the real coordinate of the CNE predicts in the analysis without chromosome names ?

**Comment by lorrainea** [comment]
You will need to compute this based on the chromosome lengths. Unfortunately CNEFinder currently only considers pairs of sequences.

**Comment by El-Castor** [comment]
Hi, 
Thanks for your explanation. Do you know a software or a way to do it ? Sorry I learn bio-informatics by myself so I didn't lot of things... =\

**Comment by lorrainea** [comment]
You can easily do this if you know the lengths of the chromosomes.
For example let's say for the reference sequence, chromosome 1 has a length of 30, chromosome 2 has a length of 20 and chromosome 3 has a length of 40.
When you concatenate them you will get an input reference sequence of length 90.
If CNEFinder outputs a ref CNE position of 40, you can compute that this is at position 10 of chromosome 2 just by adding up the lengths - I do not have a tool that does this, but you can easily compute this on python (or excel).

**Comment by dpolychr** [comment]
@El-Castor you can easily obtain chromosome lengths using bioconductor, see for instance an example workflow here:

https://msmith.de/2019/06/05/chrom-lengths-in-bioc.html

**Comment by El-Castor** [comment]
Hi Lorrainea and dpolychr,

Thanks for your respons ! 
I have the chromosome length already produce thanks dpolychr.
I will try to build a python script
