### ISSUE TITLE
Error: Reference index position is larger than size of chromosome.

### ISSUE THREAD

**Issue by paulgzlz** [lorrainea/CNEFinder#13]
Hi Lorraine,

I sometimes get the following error: 
'Error: Reference index position is larger than size of chromosome.'

This happens mostly with large input sequences (>600 Mb). The problem does not occur when I split the input files in two half-sized chunks. 

Thanks!

**Comment by lorrainea** [comment]
This should be happening when the reference index position (the values you give for parameters -a and -b) are larger than the length of the actual chromosome you are analysing.

**Comment by paulgzlz** [comment]
I am using -a 0 and -b0 (entire chromosome).
The parameters I'm using are:  -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t 0.9 -l 150 -T 56

**Comment by lorrainea** [comment]
Do you have links or attachments to your input files so I can analyse this further?

**Comment by paulgzlz** [comment]
I have uploaded my input files to this dropbox folder. 
https://www.dropbox.com/sh/5n438fmmrp81c9c/AAC5WcYVHPmaxgW5ysOabK4ba?dl=0
Please let me know if you have any trouble accessing the files.

**Comment by lorrainea** [comment]
I have updated the source code to fix this bug. Thank you for noticing! Please pull the changes and let me know if all works for you now.
