### ISSUE TITLE
negative similarity values

### ISSUE THREAD

**Issue by paulgzlz** [lorrainea/CNEFinder#14]
Hi Lorraine,

I have come across an issue where the output of CNEFinder contains similarity values that are lower than the specified threshold, and sometimes these values are negative. For example:

chr1	137269346	137269465	chr1	1201519043	1201519259	119	216	8.40
chr1	137269376	137269471	chr1	1082622145	1082624145	95	2000	-1905.26
chr1	178568463	178568678	chr1	1082622229	1082622614	215	385	13.49
chr1	178568463	178568685	chr1	1108583726	1108584184	222	458	-16.67
chr1	224256679	224256989	chr1	1082622146	1082622614	310	468	37.74
chr1	224256679	224256982	chr1	1108583632	1108584184	303	552	11.55
chr1	224927812	224927997	chr1	1082622156	1082622340	185	184	90.76

Out of dozens of runs, I have only encountered this issue with a single input fasta file (I'm linking to all files below), but I cannot tell what is wrong with it. In the example above, note that the query length (corresponding to that problematic fasta) is always higher than the reference. After extracting the corresponding sequences, I have noticed that it contains the actual CNE, followed by NNNNNN... (which should in theory be excluded). The extra length reported is due to these extra Ns.

You can download all files here:
https://www.dropbox.com/sh/1olqs71jjzxracg/AADb2QGvABYhMawmG0s9vNBia?dl=0

The problematic fasta is pfla.fa

The run parameters are: -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t 0.9 -l 150 -T 56
 
Thanks!

**Comment by lorrainea** [comment]
Hi, I have been trying to reproduce your results but have not been able to. Could I ask you to test this with a substring of your chromosomes.
So by using something like -a 220000000 -b 230000000 -c 1080000000 -d 1100000000

**Comment by paulgzlz** [comment]
Hi, when I run the command using only a subset of the chromosome, the output looks normal:
chr1	224256679	224256989	chr1	1082622146	1082622439	310	293	90.10
chr1	224927796	224927985	chr1	1082622146	1082622330	189	184	90.22

I have rerun the whole chromosome, and I still got the same problems:
chr1	137269346	137269465	chr1	1201519043	1201519259	119	216	8.40
chr1	137269376	137269471	chr1	1082622145	1082624145	95	2000	-1905.26
chr1	178568463	178568678	chr1	1082622229	1082622614	215	385	13.49
chr1	178568463	178568685	chr1	1108583726	1108584184	222	458	-16.67
chr1	224256679	224256989	chr1	1082622146	1082622614	310	468	37.74
chr1	224256679	224256982	chr1	1108583632	1108584184	303	552	11.55
chr1	224927812	224927997	chr1	1082622156	1082622340	185	184	90.76
chr1	488247588	488247759	chr1	1082622146	1082622308	171	162	90.74
chr1	488249501	488249791	chr1	1108583630	1108583902	290	272	90.07
chr1	488249518	488249826	chr1	1082622146	1082622614	308	468	34.09

**Comment by lorrainea** [comment]
Hi, I have made some changes. Please pull the new version and run your command again. Thanks
