### ISSUE TITLE
Pre-processing data consumes too much time

### ISSUE THREAD

**Issue by zoomlion** [lorrainea/CNEFinder#15]
![image](https://user-images.githubusercontent.com/36755461/126267953-8d1be1c5-5e7f-41af-a7b0-d927dc750665.png)

I used the data from the original paper as a test dataset. The running time is basically the same as that declared in the paper (8 core and 30 min). However, Pre-processing data consumes a much longer time (several hours) than real processing time. 

Is it possibly related to the IO performance?

**Comment by lorrainea** [comment]
This was related to updating the sequences due to the exon files. I have changed the code and pushed the changes, the pre-processing should be significantly faster now. Please pull and recompile.

**Comment by zoomlion** [comment]
Thank you, the updated version solved this issue perfectly.
