### ISSUE TITLE
Genome-wide identification of CNE

### ISSUE THREAD

**Issue by Miracle-Yao** [lorrainea/CNEFinder#17]
Hi @lorrainea 
Thank you for providing such a good software to identify CNE, but I have some problems.
Can CNEFinder identify CNEs genome-wide?
In fact, the minimum length of CNE may not be a fixed value, I found that CNEFinder can identify the minimum requirement of CNE is 50bp, if I want to identify more than 40bp what should I do?
I look forward to your reply.
Best wishes!
DC

**Comment by lorrainea** [comment]
Hi
With some work-arounds to the input data, you can get CNEFinder to identify CNEs genome wide, however it would be perhaps easier to just run CNEFinder several times, using an all by all comparison for all the chromosomes in the first genome against all the chromosomes in the second genome.

If you would like to find CNEs that are at least 40bp long, then you can edit the following lines of the cnef.cc file and re-compile:
Line 718 - change 50 to 40
Line 720 - change 50 to 40
Line 1283 - change 50 to 40
Line 1303 - change 50 to 40

Let me know if this works for you.
Regards
Lorraine

**Comment by Miracle-Yao** [comment]
Hi,lorrainea

Thank you for your answer. 
Although it is possible to combine all chromosome sequences into one sequence fasta file, the identified CNEs do not know from which chromosome. How should this be solved quickly.
Thanks again

I look forward to your reply.
Best wishes!
DC

**Comment by lorrainea** [comment]
You would probably need to keep a record of the starting and ending position of each chromosome within the concatenated sequence and use these values to figure out which chromosome the output CNEs are in. You would need to write some code for this so this is why I suggest doing an all by all comparison.

**Comment by Miracle-Yao** [comment]
Hi,lorrainea,
Maybe I didn't understand what you meant. Does the all by all comparison mean using CNEFinder to combine all the chromosomes of both genomes before running them separately? Is it finally merging CNEs from different chromosome combinations?
I look forward to your reply
Thanks

**Comment by lorrainea** [comment]
Hi
Sorry for the late reply. So for an all by all comparison you will not be running CNEFinder on a concatenation of the chromosomes, but rather multiple times using the pairs of different sequences. Given a dataset with 3 sequences, you would need to run CNEFinder using sequences 1 and 3, 1 and 2 and then 2 and 3. You can then proceed to analyse the results as required.
