### ISSUE TITLE
Set a maximum length for the CNE. Default:500

### ISSUE THREAD

**Issue by dpolychr** [lorrainea/CNEFinder#4]
Is this value 500 bp or 500000 bp?
A CNE can be even 1500 bp in length, so setting the default to 500 bp we are going to lose elements. Maybe put it 2000 or 5000 bp?

**Comment by lorrainea** [comment]
It is 500bp and can change, the minimum length -l controls what the length should be and the user can input 500, 1000 or 2000, but I will change it to 2000.
