### ISSUE TITLE
output similarity value lower than -t similarity threshold

### ISSUE THREAD

**Issue by paulgzlz** [lorrainea/CNEFinder#6]
I ran cnefinder with the following command:
./cnef -r aaur_atl.fa -q aaur_cal.fa -e aaur_atl_cumul.exons -f aaur_cal_cumul.exons -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t 0.95 -l 150 -T 8  -o output/aaur_atl_vs_aur_cal.out

Even though the -t parameter is set at 0.95, all of the CNEs in the output are lower than 95. Is it normal? Here is the beginning of the output:

chr1	10526770	10526937	chr1	46532823	46532990	167	167	46.11
chr1	12204599	12204769	chr1	262826972	262827142	170	170	44.12
chr1	12752234	12752385	chr1	97269541	97269692	151	151	49.01
chr1	14712117	14712274	chr1	245015215	245015372	157	157	36.94
chr1	14712301	14712469	chr1	245015402	245015569	168	167	52.10
chr1	16740978	16741138	chr1	121032227	121032388	160	161	31.25
chr1	17202505	17202658	chr1	78271869	78272019	153	150	44.67
chr1	17675942	17676093	chr1	113301365	113301517	151	152	46.36
chr1	18058577	18058750	chr1	183446768	183446941	173	173	39.88

**Comment by lorrainea** [comment]
Hi, could you send over your input files so I can understand more of what's going on in the code. Thanks.

**Comment by paulgzlz** [comment]
Hi Lorraine, thanks for your quick reply! Here are the exon files and output. The fasta files are ~300MB, I'm not sure how to send them to you. 

[exon_and_output.zip](https://github.com/lorrainea/CNEFinder/files/4067394/exon_and_output.zip)

**Comment by lorrainea** [comment]
You can upload them externally then send me the link

**Comment by paulgzlz** [comment]
Here are the two fasta files: https://www.dropbox.com/s/bd3g2jp8oq8ah0f/fasta%20files.zip?dl=0

**Comment by lorrainea** [comment]
The exons files and fasta files you have sent are different from those in the command you have written. Have they just been renamed or are they different sequences?

**Comment by paulgzlz** [comment]
Sorry, I ran many commands with different species, but the same parameters for all. The command that corresponds to the files I've shared is:
./cnef -r exon_files/aaur_atl.fa -q exon_files/dgig.fa -e exon_files/aaur_atl_cumul.exons -f exon_files/dgig_cumul.exons -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t 0.95 -l 150 -T 8 -o cnidarian_output/aaur_atl_vs_gig.out

**Comment by lorrainea** [comment]
Do you have a sample of your output for this where the threshold output is <95?

**Comment by paulgzlz** [comment]
Yes. I also shared the entire output file yesterday.
chr1	1290969	1291123	chr1	283928375	283928530	154	155	41.56
chr1	1345309	1345464	chr1	266220377	266220532	155	155	44.52
chr1	1667222	1667396	chr1	157272781	157272955	174	174	43.10
chr1	2739764	2739920	chr1	134891895	134892052	156	157	39.10
chr1	2739949	2740107	chr1	134892080	134892238	158	158	22.78
chr1	5690761	5690914	chr1	139323565	139323719	153	154	39.87
chr1	5997384	5997557	chr1	183446768	183446941	173	173	39.88
chr1	6926686	6926864	chr1	25126331	25126511	178	180	45.51
chr1	7407853	7408006	chr1	264875508	264875660	153	152	50.66
chr1	7462316	7462487	chr1	264940998	264941170	171	172	48.54
chr1	9892124	9892297	chr1	202363229	202363401	173	172	34.88

**Comment by lorrainea** [comment]
Indeed you have...are you sure you have pulled the latest version of CNEFinder as I am unable to replicate the results you have shown here. I attach the results I get when running the command: 
./cnef -r aaur_atl.fa -q dgig.fa -e aaur_atl_cumul.exons -f dgig_cumul.exons -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t 0.95 -l 150 -o output_aaur_atl_vs_aur_cal.out
[output_aaur_atl_vs_aur_cal.out.txt](https://github.com/lorrainea/CNEFinder/files/4076772/output_aaur_atl_vs_aur_cal.out.txt)

**Comment by paulgzlz** [comment]
It looks like the problem only occurs when I submit several jobs to my cluster using swarm. When I run a single job using sbatch instead, the output is normal, with all similarity values above the threshold. Does that make any sense to you? Anyway, the problem is probably on my side. Thank you so much for your help!

**Comment by paulgzlz** [comment]
Just a thought: cnefinder creates two files (new_query.fa  new_ref.fa) in the working directory. Could my problem be due to different jobs overwriting these files as they are running at the same time in the same directory?

**Comment by lorrainea** [comment]
Thanks for pointing this out, I will look into this further.

**Comment by paulgzlz** [comment]
I am closing this issue now, the problem only occurs when running several cnefinder jobs at the same time in the same working directory. Maybe it would be a good idea to mention not to do that in the wiki? Thanks.

**Comment by lorrainea** [comment]
Thanks, this has now been updated to allow for running parallel jobs.
