### ISSUE TITLE
CNEs identified within exons

### ISSUE THREAD

**Issue by paulgzlz** [lorrainea/CNEFinder#7]
Hello, I ran cnefinder and noticed that many CNEs in the output are located within exons.

I ran the following command:

/data/gonzalezp2/cnefinder_latest_version/CNEFinder/cnef -r /data/gonzalezp2/cnefinder_metazoa/cnefinder_04_28_20/cnefinder_input/fasta/hvul.fa -q /data/gonzalezp2/cnefinder_metazoa/cnefinder_04_28_20/cnefinder_input/fasta_previous_runs/hrob.fa -e /data/gonzalezp2/cnefinder_metazoa/cnefinder_04_28_20/cnefinder_input/exons/hvul.exons -f /data/gonzalezp2/cnefinder_metazoa/cnefinder_04_28_20/cnefinder_input/exons_previous_runs/hrob.exons -y 1 -z 1 -a 0 -b 0 -c 0 -d 0 -t 0.9 -l 150 -T 32  -o hvul_vs_hrob.out

I have uploaded the fasta, exon files and cnefinder output to a dropbox folder: 
https://www.dropbox.com/sh/e8lb0d1q8u6olm7/AADaehfl0jyqPfYoM6IfjJKca?dl=0

The folder also contains a file, hrob_cnes_in_exons.tsv, that shows the cnes from the cnefinder output file that are located within an exon in the exon file (for the species hrob). The columns of this file are:
cf_out_line: line number in cnefinder output file
query_chrom: chromosome
query_start: start coordinate of cne
query_end: end coordinate of cne
exon_file_line: line number of exon file
chromosome: chromosome in exon file
start: start coordinate of exon overlapping the cne
end: end coordinate of exon overlapping the cne
id: exon id
status: exon status
strand: exon strand

Please let me know if you need any additional information, and thank you very much.
~Paul

**Comment by lorrainea** [comment]
Thank you for noticing, I have updated the code so if you pull the update, your output should no longer include CNEs which occur in exon coordinates.

**Comment by paulgzlz** [comment]
Thank you, I just looked at the output of a new run and the problem is fixed.

**Comment by fka21** [comment]
Hey! 

I have encountered a similar issue myself with different genomes. I have the latest release of CNEFinder and followed the genome preparation steps as outlined in the wiki. 

Here is a link for the data and script I used to generate the results:
https://www.dropbox.com/scl/fo/3xwszha6rkdineyq480rg/h?dl=0&rlkey=qkippocujnxpepgnywlne69p6

The exon_examples file contains a few examples of results which fall into exonic regions which were verified manually on UCSC genome browser for zebrafish.  The danio_v_gar.tsv file is just a concatenated file of the results for each chromosome.

Please let me know if you managed to figure out what could be at the root of our issue. 

Thank you very much,
Ferenc

**Comment by lorrainea** [comment]
Hello, please note that your exon files must be TSV files. I believe your values are currently separated using spaces. I will make a note of this on the Wiki page.

**Comment by fka21** [comment]
Hey, apologies for the confusion. Thank you for the heads-up.
