### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by bandlaas** [lorrainea/CNEFinder#8]
make -f Makefile_M
g++-7 -g -fopenmp -D_USE_OMP -msse4.2 -O3 -fomit-frame-pointer -funroll-loops  -c -lm -I ./ cnef.cc 
cnef.cc:26:10: fatal error: boost/algorithm/string.hpp: No such file or directory
 #include <boost/algorithm/string.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [cnef.o] Error 1

Hello, newbie to GitHub. I am working 10.10.5 (OS X Yosemite) and after lot of hurdles I was able to install boost. The only library that I have not installed is seqAn. I am following the homebrew methods for installation of libraries and other required items. However, homebrew was unable ot install seqAn. 

I tried to execute the command and I received the above error. I would appreciate any guidance on how to proceed forward to install it correctly. 

Thank you!

**Comment by lorrainea** [comment]
Thank you for noticing, SeqAn is no longer required by CNEFinder so you do not need to install it.
Did you run the $ ./pre-install.sh command before you compiled?

**Comment by bandlaas** [comment]
" ./pre-install.sh
unzip:  cannot find or open boost.zip, boost.zip.zip or boost.zip.ZIP."

This is the error I receive when I run pre-install command. However, when I look into installation instructions its mentions as "For Linux, you can install these libraries via $ ./pre-install.sh". I manually installed the supporting files namely C++ compile/gcc@7, cmake, boost. 

Not sure if thats the way to do it or through /.pre-install.sh. Hoping that all the files were installed I tried to follow the instructions to compile the CNE Finder.

Also, I quickly started running a Linux OS and it was dead simple to install. It took me less than 5 minutes to install on a Linux OS. Not sure why I can get it work on my Mac OS X 10.10 Yosemite.

**Comment by lorrainea** [comment]
So CNEFinder needs to have the boost zip file installed in it's location for this error to be resolved, it seems it was deleted while pre-installing a previous time. Can you pull again and make sure you have the boost.zip file in your CNEFinder directory. Then run $ ./pre-install.sh

**Comment by bandlaas** [comment]
Wonderful! Its working now. Like you mentioned boost zip file was not in wrong location. I put it where it is supposed to be and everything works now. Thank you for prompt response.
